branches:
  only:
    - master

environment:
  matrix:
    - PYTHON: "C:\\Python38"
      PYTHON_VERSION: "3.8.0"
      PYTHON_ARCH: "32"

install:
  - "%PYTHON%\\python.exe -m pip install poetry"
  - "%PYTHON%\\python.exe -m poetry install"

build: off

test_script: "%PYTHON%\\python.exe -m poetry run pytest"
