branches:
  only:
    - master

environment:
  matrix:
    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: "3.6.6"
      PYTHON_ARCH: "32"
    - PYTHON: "C:\\Python37"
      PYTHON_VERSION: "3.7.0"
      PYTHON_ARCH: "32"

install:
  - "%PYTHON%\\python.exe -m pip install pipenv"
  - "%PYTHON%\\python.exe -m pipenv install --dev"

build: off

test_script: "%PYTHON%\\python.exe -m pipenv run pytest"
